name: villavibe
description: A unified vacation rental app for Guests and Hosts.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Navigation
  go_router: ^13.2.0

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.0

  # UI & Assets
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.10
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  flutter_animate: ^4.5.0

  # Utilities
  intl: ^0.19.0
  syncfusion_flutter_datepicker: ^25.1.35
  uuid: ^4.3.3
  shared_preferences: ^2.5.3
  wolt_modal_sheet: ^0.11.0
  lucide_icons: ^0.257.0
  google_maps_flutter: ^2.14.0
  geolocator: ^14.0.2
  http: ^1.6.0
  qr_flutter: ^4.1.0
  geocoding: ^4.0.0
  image_picker: ^1.2.1
  mobile_scanner: ^7.1.3
  cloud_functions: ^5.6.2
  webview_flutter: ^4.13.0
  webview_flutter_web: ^0.2.3+4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  riverpod_generator: ^2.4.0
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
